version: '{branch}.{build}'
branches:
  only:
  - master

image: Visual Studio 2017

environment:
  PHP_SDK_BINARY_TOOLS_VER: php-sdk-2.0.9

  matrix:
    - ARCH: x86
      PHP_VER: 7.2
      VC_VER: vc15
    - ARCH: x64
      PHP_VER: 7.2
      VC_VER: vc15
install:
- cmd: cinst wget
build_script:
- cmd: >-
    "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %ARCH%

    wget https://github.com/OSTC/php-sdk-binary-tools/archive/%PHP_SDK_BINARY_TOOLS_VER%.zip --no-check-certificate -q -O php-sdk-binary-tools-%PHP_SDK_BINARY_TOOLS_VER%.zip

    7z x -y php-sdk-binary-tools-%PHP_SDK_BINARY_TOOLS_VER%.zip -oC:\projects

    move C:\projects\php-sdk-binary-tools-%PHP_SDK_BINARY_TOOLS_VER% C:\projects\php-sdk
    
    C:\projects\php-sdk\phpsdk-%VC_VER%-%ARCH%.bat

    git clone https://github.com/php/php-src C:\projects\php-src -b PHP-%PHP_VER% --depth=1

    mkdir C:\projects\php-src\ext\ast

    xcopy C:\projects\php-ast C:\projects\php-src\ext\ast /s /e /y /q

    cd C:\projects\php-src

    phpsdk_deps -u

    buildconf.bat

    configure.bat --disable-all --enable-cli --enable-cgi --enable-zts --enable-ast=shared --with-prefix=C:\projects\php-ast\bin --with-php-build=deps

    nmake

    nmake install

    cd C:\projects\php-ast\bin

    echo [PHP] > php.ini

    echo extension_dir = "ext" >> php.ini

    echo extension=php_ast.dll >> php.ini

    set TEST_PHP_EXECUTABLE=%cd%\php.exe

    php -v

    php -m
test_script:
- cmd: php.exe /projects/php-src/run-tests.php /projects/php-src/ext/ast -q --show-diff
artifacts:
  - path: bin
    name: master
    type: zip
